import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
import { organs, hormones, bodyCases } from './body.js';

// Educational mannequin: positions are approximate, not a segmented anatomical atlas.
// x points to the subject's left, y superior, z anterior. In frontal view the liver is at screen left.
export function createBodyViewer({state,onSelect,onFailure}) {
 const host=document.querySelector('#bodyCanvas'),overlay=document.querySelector('#bodyLabels');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,60);
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.appendChild(renderer.domElement);
 renderer.domElement.setAttribute('aria-label','Cuerpo humano 3D orientable. Selecciona un órgano en el modelo o en la lista.');renderer.domElement.tabIndex=0;
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=5;controls.maxDistance=22;controls.minPolarAngle=.2;controls.maxPolarAngle=Math.PI-.2;
 scene.add(new THREE.HemisphereLight(0xd7f4ff,0x21314c,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-4,8,7);scene.add(light);const rim=new THREE.DirectionalLight(0x61cfc8,2);rim.position.set(5,4,-4);scene.add(rim);
 const skin=new THREE.MeshPhongMaterial({color:0x91b8c8,transparent:true,opacity:.19,shininess:55,side:THREE.FrontSide,depthWrite:false});
 const allSkin=[],parts={},anchors={},labels={},flowGroup=new THREE.Group(),paths=[];scene.add(flowGroup);
 function material(color){return new THREE.MeshPhongMaterial({color,emissive:color,emissiveIntensity:.08,shininess:35,transparent:true,opacity:.85});}
 function add(geometry,mat,position=[0,0,0],scale=[1,1,1],id){const m=new THREE.Mesh(geometry,mat);m.position.set(...position);m.scale.set(...scale);scene.add(m);if(id){m.userData.organ=id;(parts[id]??=[]).push(m);}else if(mat===skin)allSkin.push(m);return m;}
 function ellipsoid(pos,scale,mat,id){return add(new THREE.SphereGeometry(1,32,24),mat,pos,scale,id);}
 function tube(points,radius,mat,id){return add(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p))),64,radius,10,false),mat,[0,0,0],[1,1,1],id);}
 function limb(a,b,r1,r2){const from=new THREE.Vector3(...a),to=new THREE.Vector3(...b),delta=to.clone().sub(from);const m=add(new THREE.CylinderGeometry(r2,r1,delta.length(),32,4),skin,from.clone().add(to).multiplyScalar(.5).toArray());m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());ellipsoid(a,[r1,r1,r1],skin);ellipsoid(b,[r2,r2,r2],skin);}
 // Smooth elliptical rings form a continuous torso, waist and pelvis.
 const profile=[[3.05,.26,.24],[3.22,.52,.31],[3.48,.64,.37],[3.8,.6,.35],[4.15,.48,.3],[4.5,.5,.33],[4.9,.64,.38],[5.3,.74,.4],[5.65,.79,.34],[5.85,.63,.27],[6.02,.29,.22]];
 const spline=new THREE.CatmullRomCurve3(profile.map(([y,x,z])=>new THREE.Vector3(x,y,z))),positions=[],indices=[];const rings=72,sides=64;
 for(let j=0;j<=rings;j++){const p=spline.getPoint(j/rings);for(let i=0;i<=sides;i++){const a=i/sides*Math.PI*2;positions.push(p.x*Math.cos(a),p.y,p.z*Math.sin(a));if(j<rings&&i<sides){const k=j*(sides+1)+i;indices.push(k,k+sides+1,k+1,k+1,k+sides+1,k+sides+2);}}}
 const torso=new THREE.BufferGeometry();torso.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));torso.setIndex(indices);torso.computeVertexNormals();add(torso,skin);
 limb([0,5.95,0],[0,6.4,0],.22,.23);ellipsoid([0,6.91,0],[.43,.57,.4],skin);ellipsoid([0,6.65,.11],[.31,.3,.31],skin);
 ellipsoid([0,6.88,.4],[.09,.15,.13],skin);for(const s of [-1,1]){ellipsoid([s*.43,6.88,0],[.075,.16,.1],skin);limb([s*.72,5.68,0],[s*1.04,4.65,0],.24,.18);limb([s*1.04,4.65,0],[s*1.24,3.67,.08],.18,.115);ellipsoid([s*1.28,3.42,.09],[.14,.28,.085],skin);for(let i=0;i<4;i++)limb([s*(1.19+i*.055),3.25,.09],[s*(1.2+i*.06),3.01+Math.abs(i-1.5)*.055,.09],.028,.022);limb([s*1.17,3.48,.09],[s*1.08,3.26,.14],.045,.032);limb([s*.34,3.28,0],[s*.39,1.88,0],.29,.2);limb([s*.39,1.88,0],[s*.41,.46,0],.19,.105);ellipsoid([s*.41,.2,.18],[.16,.18,.34],skin);}
 const floor=new THREE.Mesh(new THREE.CircleGeometry(1.7,64),new THREE.MeshBasicMaterial({color:0x284757,transparent:true,opacity:.25,depthWrite:false}));floor.rotation.x=-Math.PI/2;floor.position.y=.015;scene.add(floor);
 const coordinates={brain:[0,7.04,0],hypo:[0,6.79,.08],pit:[0,6.63,.14],stem:[0,6.62,-.17],thyroid:[0,6.12,.15],heart:[.18,5.23,.12],liver:[-.31,4.69,.12],stomach:[.33,4.51,.1],adrenal:[.39,4.51,-.2],kidney:[-.4,4.3,-.22],gut:[0,3.91,.15],fat:[-.5,3.67,.08],gonads:[.24,3.37,.05]};
 for(const [id,p] of Object.entries(coordinates))anchors[id]=new THREE.Vector3(...p);
 const colors={brain:0xbca4e7,hypo:0xffa36c,pit:0xff8094,stem:0xc1a085,thyroid:0x79ded0,heart:0xeb6f8a,liver:0xbe7856,stomach:0xf7b36d,adrenal:0xffd38a,kidney:0xba6d8b,gut:0xe9be8e,fat:0xe2cb71,gonads:0xc6a1ed};
 const mats=Object.fromEntries(Object.entries(colors).map(([id,c])=>[id,material(c)]));
 // Stylised organ volumes. Tiny nuclei and the pituitary are deliberately enlarged for picking.
 for(const s of [-1,1])ellipsoid([s*.14,7.06,0],[.2,.28,.29],mats.brain,'brain');
 ellipsoid(coordinates.hypo,[.075,.055,.065],mats.hypo,'hypo');ellipsoid(coordinates.pit,[.065,.05,.06],mats.pit,'pit');tube([[0,6.91,-.19],[0,6.7,-.2],[0,6.46,-.1]],.065,mats.stem,'stem');
 for(const s of [-1,1])ellipsoid([s*.105,6.12,.17],[.07,.14,.055],mats.thyroid,'thyroid');tube([[-.1,6.12,.17],[0,6.08,.19],[.1,6.12,.17]],.04,mats.thyroid,'thyroid');
 const heart=ellipsoid(coordinates.heart,[.17,.25,.16],mats.heart,'heart');heart.rotation.z=.3;
 const liver=ellipsoid(coordinates.liver,[.42,.17,.24],mats.liver,'liver');liver.rotation.z=-.15;ellipsoid([.05,4.72,.12],[.26,.11,.2],mats.liver,'liver');
 tube([[.19,4.99,.04],[.19,4.76,.07],[.35,4.6,.12],[.39,4.43,.14],[.29,4.33,.16],[.16,4.36,.16]],.1,mats.stomach,'stomach');ellipsoid([.35,4.48,.12],[.15,.2,.14],mats.stomach,'stomach');
 for(const s of [-1,1]){const g=new THREE.SphereGeometry(1,32,24),p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setX(i,x+.22*Math.exp(-y*y*7));}g.computeVertexNormals();const k=add(g,mats.kidney,[s*.4,4.3,-.22],[.13,.22,.12],'kidney');k.rotation.z=-s*.15;ellipsoid([s*.4,4.53,-.2],[.13,.055,.08],mats.adrenal,'adrenal');ellipsoid([s*.52,3.66,.03],[.105,.28,.2],mats.fat,'fat');ellipsoid([s*.24,3.37,.05],[.065,.085,.065],mats.gonads,'gonads');}
 const gutPoints=[];for(let i=0;i<=80;i++){const t=i/80;gutPoints.push([Math.sin(t*Math.PI*10)*.32,4.2-t*.62,.13+Math.cos(t*Math.PI*10)*.05]);}tube(gutPoints,.045,mats.gut,'gut');
 const vesselMat=new THREE.MeshBasicMaterial({color:0xd56880,transparent:true,opacity:.3});tube([[0,6.2,-.05],[-.07,5.45,-.03],[0,4.7,-.04],[0,3.42,-.04]],.022,vesselMat);
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let paused=false,phase=0,last=0,active=new Set(),signature='',failed=false;
 const routeSpecs={ghrelin:[['stomach','hypo']],leptin:[['fat','hypo']],cck:[['gut','stem','hypo']],orexin:[['hypo','stem','brain']],adh:[['hypo','pit','kidney']],angio:[['kidney','hypo']],cortisol:[['hypo','pit','adrenal'],['adrenal','hypo']],catechol:[['stem','adrenal','heart']],oxytocin:[['hypo','pit','heart'],['hypo','brain']],testo:[['hypo','pit','gonads'],['gonads','hypo']],thyroid:[['hypo','pit','thyroid'],['thyroid','hypo']]};
 function clearFlows(){for(const child of [...flowGroup.children]){flowGroup.remove(child);child.geometry?.dispose();child.material?.dispose();}paths.length=0;}
 function buildFlows(ids){clearFlows();for(const id of ids){const h=hormones[id];for(const [index,route] of routeSpecs[id].entries()){const feedback=index>0&&!!h.feedback,points=[];for(let i=0;i<route.length;i++){const a=anchors[route[i]].clone();points.push(a);if(i<route.length-1){const b=anchors[route[i+1]],mid=a.clone().lerp(b,.5);mid.x+=feedback?-.3:.13;mid.z+=.25;points.push(mid);}}const curve=new THREE.CatmullRomCurve3(points);const geo=new THREE.BufferGeometry().setFromPoints(curve.getPoints(80));const mat=feedback?new THREE.LineDashedMaterial({color:h.color,dashSize:.07,gapSize:.06,depthTest:false,transparent:true,opacity:.75}):new THREE.LineBasicMaterial({color:h.color,depthTest:false,transparent:true,opacity:.9});const line=new THREE.Line(geo,mat);line.computeLineDistances();line.renderOrder=8;flowGroup.add(line);const dots=Array.from({length:3},()=>{const dot=new THREE.Mesh(new THREE.SphereGeometry(.035,10,8),new THREE.MeshBasicMaterial({color:h.color,depthTest:false}));dot.renderOrder=9;flowGroup.add(dot);return dot;});paths.push({curve,dots});}}}
 const leaders=document.createElementNS('http://www.w3.org/2000/svg','svg');overlay.appendChild(leaders);
 for(const [id,o] of Object.entries(organs)){const b=document.createElement('button');b.className='body-organ-label';b.textContent=o.label||o.name;b.dataset.organ=id;b.style.setProperty('--organ-color','#'+colors[id].toString(16));overlay.appendChild(b);labels[id]=b;}
 function layoutLabels(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;const entries=[];for(const [id,b] of Object.entries(labels)){b.hidden=!active.has(id);if(b.hidden)continue;const p=anchors[id].clone().project(camera);entries.push({id,b,x:(p.x*.5+.5)*w,y:(-.5*p.y+.5)*h,left:organs[id].side==='left'});}leaders.setAttribute('viewBox',`0 0 ${w} ${h}`);for(const left of [true,false]){const list=entries.filter(x=>x.left===left).sort((a,b)=>a.y-b.y);let y=35;for(const e of list){e.labelY=Math.max(y,Math.min(h-35,e.y));y=e.labelY+36;}if(y>h-15){const delta=y-h+15;list.forEach(e=>e.labelY-=delta);}}leaders.innerHTML=entries.map(e=>{const x=e.left?8:w-8;e.b.style.left=x+'px';e.b.style.top=e.labelY+'px';e.b.style.transform=e.left?'translateY(-50%)':'translate(-100%,-50%)';const end=e.left?x+e.b.offsetWidth:x-e.b.offsetWidth;return `<path d="M${e.x},${e.y} L${end},${e.labelY}" stroke="#${colors[e.id].toString(16)}" fill="none" opacity=".8"/><circle cx="${e.x}" cy="${e.y}" r="2.5" fill="#${colors[e.id].toString(16)}"/>`;}).join('');}
 function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);}
 new ResizeObserver(resize).observe(host);
 function reset(view='front'){controls.target.set(0,3.8,0);const d=13.8;camera.position.set(...({front:[0,3.8,d],side:[d,3.8,0],back:[0,3.8,-d]})[view]);controls.update();document.querySelector('#bodyOrientation').textContent={front:'Vista anterior · derecha del cuerpo a tu izquierda',side:'Vista lateral izquierda',back:'Vista posterior'}[view];resize();}
 controls.addEventListener('start',()=>{document.querySelector('#bodyOrientation').textContent='Vista libre · arrastra para girar';});
 function update(){if(failed)return;const b=state.bodyState,s=b.tab==='cases'?bodyCases[b.bcase].steps[b.bstep]:null,ids=s?s.flows:[b.hormone];active=new Set(s?s.organs:[hormones[b.hormone].source]);for(const id of ids)for(const r of routeSpecs[id])for(const o of r)active.add(o);if(b.organ&&b.tab==='hormones')active.add(b.organ);const next=ids.join('|');if(next!==signature){signature=next;buildFlows(ids);}for(const [id,mat] of Object.entries(mats)){mat.opacity=active.has(id)?1:.28;mat.emissiveIntensity=active.has(id)?.24:.025;for(const m of parts[id]||[])m.renderOrder=active.has(id)?3:1;}const details={cortisol:'Eje HPA: CRH → ACTH → cortisol; retorno discontinuo = retroalimentación',testo:'Eje HPG: GnRH → LH/FSH → hormonas gonadales',thyroid:'Eje HPT: TRH → TSH → T3/T4',cck:'CCK intestinal y señal vagal hacia el tronco encefálico',orexin:'Orexinas: comunicación neural dentro del encéfalo',catechol:'Señal simpática → suprarrenal → catecolaminas en sangre',oxytocin:'Liberación periférica y vías centrales distintas; corazón = circulación sistémica',angio:'Renina renal → cascada de angiotensina II → señal al cerebro',adh:'Síntesis hipotalámica → liberación en neurohipófisis → riñón'};document.querySelector('#bodyFlowKey').textContent=ids.length?ids.map(id=>details[id]||hormones[id].name+' · comunicación por la circulación').join(' · '):'Sin mensajeros destacados en este paso';document.querySelector('#bodyOrganSelect').value=b.organ||'';resize();}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;
 renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(Object.values(parts).flat());if(hits.length)onSelect(hits[0].object.userData.organ);down=null;});
 renderer.domElement.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Home'].includes(e.key)){e.preventDefault();if(e.key==='Home')reset();else{const offset=camera.position.clone().sub(controls.target),spherical=new THREE.Spherical().setFromVector3(offset);if(e.key==='ArrowLeft')spherical.theta-=.15;if(e.key==='ArrowRight')spherical.theta+=.15;if(e.key==='ArrowUp')spherical.phi=Math.max(.2,spherical.phi-.15);if(e.key==='ArrowDown')spherical.phi=Math.min(Math.PI-.2,spherical.phi+.15);if(e.key==='+')spherical.radius=Math.max(5,spherical.radius*.9);if(e.key==='-')spherical.radius=Math.min(22,spherical.radius*1.1);camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(spherical));controls.update();}}});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();failed=true;onFailure();});
 function animate(t){requestAnimationFrame(animate);const dt=Math.min((t-last)/1000,.05)||0;last=t;if(failed||state.home||state.mode!=='body'||document.hidden)return;if(!paused&&!reduced)phase+=dt;controls.update();for(const f of paths)f.dots.forEach((d,i)=>d.position.copy(f.curve.getPoint((phase*.18+i/3)%1)));layoutLabels();renderer.render(scene,camera);}

 // Reuse the already licensed fsaverage cortex in the head, without claiming whole-body atlas precision.
 fetch('./anatomy/brain.json').then(r=>{if(!r.ok)throw Error('brain');return r.json();}).then(data=>{const replacement=[];for(const side of ['left','right']){const d=data.cortex[side],g=new THREE.BufferGeometry(),p=[];for(let i=0;i<d.positions.length;i+=3)p.push(-d.positions[i+2]*.19,7.03+d.positions[i+1]*.17,-d.positions[i]*.19);g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(d.indices);g.computeVertexNormals();replacement.push(new THREE.Mesh(g,mats.brain));}for(const old of parts.brain){scene.remove(old);old.geometry.dispose();}parts.brain=replacement;for(const m of replacement){m.userData.organ='brain';scene.add(m);}update();}).catch(()=>{/* The simplified brain remains available if the reference mesh cannot load. */});

 reset();update();requestAnimationFrame(animate);
 return {update,reset,setOpacity:value=>{skin.opacity=value;},togglePause:()=>{paused=!paused;return paused;},zoom:factor=>{const offset=camera.position.clone().sub(controls.target);offset.setLength(THREE.MathUtils.clamp(offset.length()*factor,5,22));camera.position.copy(controls.target).add(offset);controls.update();}};
}
