import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
export async function createBrainViewer({state,regions,edges,edgeColor,activeRegions,activeEdges,edgeStrength,gate,selectRegion,highlightId=()=>null,onResize}){
 const host=document.querySelector('#canvasHost'),labelHost=document.querySelector('#labels'),loading=document.querySelector('#visualLoading');
 const response=await fetch('./anatomy/brain.json');if(!response.ok)throw new Error('No se pudo cargar el modelo anatómico');const data=await response.json();
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,50);camera.position.set(0,.4,8.4);camera.up.set(0,1,0);
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Modelo de referencia fsaverage con estructuras bilaterales. Las etiquetas y los botones de vista permiten explorar sin arrastrar.');
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=13;controls.target.set(.1,0,0);
 scene.add(new THREE.HemisphereLight(0xe8f2ff,0x263244,2.1));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(-4,5,6);scene.add(key);const fill=new THREE.DirectionalLight(0xaccaff,1.5);fill.position.set(2,1,-5);scene.add(fill);
 const cortical=[],refs=[],meshes={},labels={},anchors={};
 function geometry(d){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(d.positions,3));g.setIndex(d.indices);g.computeVertexNormals();return g;}
 const sides=['left','right'];
 for(const side of sides){const d=data.cortex[side],g=geometry(d),colors=[];for(const family of d.family){const c=new THREE.Color(family===1?0x537caf:0x849aa6);colors.push(c.r,c.g,c.b);}g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const mat=new THREE.MeshPhongMaterial({vertexColors:true,transparent:true,opacity:state.opacity,side:THREE.DoubleSide,depthWrite:false,shininess:12});const m=new THREE.Mesh(g,mat);m.userData.side=side;scene.add(m);cortical.push(m);}
 for(const [id,part] of Object.entries(data.reference))for(const [side,d] of Object.entries(part)){const m=new THREE.Mesh(geometry(d),new THREE.MeshPhongMaterial({color:id==='thalamus'?0x8e9fae:0x697d8b,transparent:true,opacity:.23,depthWrite:false}));m.userData.side=side;scene.add(m);refs.push(m);}
 // These three structures have no independent aseg label: keep wireframe markers explicit.
 data.regions.snc={left:{anchor:[.44,-.6,.22],radii:[.12,.1,.08],schematic:true},right:{anchor:[.44,-.6,-.22],radii:[.12,.1,.08],schematic:true}};
 // Marcadores aproximados añadidos en la v3 (sin segmentación propia en el conjunto de datos).
 data.regions.vmpfc={left:{anchor:[-1.02,-0.5,0.13],radii:[0.2,0.13,0.07],schematic:true},right:{anchor:[-1.02,-0.5,-0.13],radii:[0.2,0.13,0.07],schematic:true}};
 data.regions.insula={left:{anchor:[-0.18,-0.24,0.92],radii:[0.34,0.22,0.05],schematic:true},right:{anchor:[-0.18,-0.24,-0.92],radii:[0.34,0.22,0.05],schematic:true}};
 data.regions.lh={left:{anchor:[0.09,-0.54,0.15],radii:[0.055,0.05,0.045],schematic:true},right:{anchor:[0.09,-0.54,-0.15],radii:[0.055,0.05,0.045],schematic:true}};
 data.regions.vmh={left:{anchor:[0.1,-0.63,0.045],radii:[0.05,0.045,0.04],schematic:true},right:{anchor:[0.1,-0.63,-0.045],radii:[0.05,0.045,0.04],schematic:true}};
 data.regions.pit={left:{anchor:[-0.02,-0.86,0.02],radii:[0.07,0.06,0.05],schematic:true},right:{anchor:[-0.02,-0.86,-0.02],radii:[0.07,0.06,0.05],schematic:true}};
 data.regions.sara={left:{anchor:[0.62,-1.0,0.05],radii:[0.1,0.42,0.07],schematic:true},right:{anchor:[0.62,-1.0,-0.05],radii:[0.1,0.42,0.07],schematic:true}};

 for(const [id,r] of Object.entries(regions)){meshes[id]=[];anchors[id]={};for(const side of sides){const d=data.regions[id][side];anchors[id][side]=new THREE.Vector3(...d.anchor);const mat=new THREE.MeshPhongMaterial({color:r.color,emissive:r.color,emissiveIntensity:.08,transparent:true,opacity:.85,side:THREE.DoubleSide,shininess:22,wireframe:!!d.schematic,polygonOffset:!d.schematic,polygonOffsetFactor:-1,polygonOffsetUnits:-1});let m;if(d.schematic){m=new THREE.Mesh(new THREE.SphereGeometry(1,12,8),mat);m.scale.set(...d.radii);m.position.copy(anchors[id][side]);}else m=new THREE.Mesh(geometry(d),mat);m.userData={id,side,schematic:!!d.schematic};scene.add(m);meshes[id].push(m);}const label=document.createElement('button');label.className='region-label';label.style.setProperty('--region-color','#'+r.color.toString(16).padStart(6,'0'));label.textContent=r.short;label.setAttribute('aria-label',`Explorar ${r.name}`);label.onclick=()=>selectRegion(id);labelHost.appendChild(label);labels[id]=label;}
 const leaders=document.createElementNS('http://www.w3.org/2000/svg','svg');leaders.setAttribute('class','label-leaders');labelHost.prepend(leaders);
 const flows=[];for(const [i,e] of edges.entries())for(const side of sides){const a=anchors[e[0]][side],b=anchors[e[1]][side],mid=a.clone().lerp(b,.5);mid.z+=(side==='left'?1:-1)*.13;mid.y+=(i%2?.08:-.08);const curve=new THREE.QuadraticBezierCurve3(a,mid,b);const lineGeo=new THREE.BufferGeometry().setFromPoints(curve.getPoints(40));const material=e[3]==='indirect'?new THREE.LineDashedMaterial({color:edgeColor(e),dashSize:.07,gapSize:.05,transparent:true,opacity:.8,depthTest:false}):new THREE.LineBasicMaterial({color:edgeColor(e),transparent:true,opacity:.8,depthTest:false});const line=new THREE.Line(lineGeo,material);line.computeLineDistances();line.renderOrder=5;scene.add(line);const dots=Array.from({length:3},()=>{const m=new THREE.Mesh(new THREE.SphereGeometry(.021,8,6),new THREE.MeshBasicMaterial({color:edgeColor(e),transparent:true,depthTest:false}));m.renderOrder=6;scene.add(m);return m;});flows.push({i,e,side,curve,line,dots});}
 let desiredPosition=null,desiredTarget=null,phase=0,last=0,glowing=[],lastFocus=null;
 function sideVisible(side){return side==='midline'||state.hemisphere==='both'||state.hemisphere===side;}
 function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);}
 new ResizeObserver(()=>{resize();onResize();}).observe(document.querySelector('#brainViewport'));
 function preset(name){const p={left:[0,.35,8.4],right:[0,.35,-8.4],medial:[.2,.25,-8.4],inferior:[0,-8.5,.01],superior:[0,8.5,.01]};if(!p[name])return;if(['left','right','medial'].includes(name)){state.hemisphere=name==='right'?'right':'left';document.querySelector('#hemisphere').value=state.hemisphere;}camera.up.set(0,name==='inferior'||name==='superior'?0:1,name==='inferior'?-1:name==='superior'?1:0);desiredPosition=new THREE.Vector3(...p[name]);desiredTarget=new THREE.Vector3(.1,0,0);document.querySelector('#orientation').textContent={left:'Vista lateral izquierda',right:'Vista lateral derecha',medial:'Vista medial izquierda · hemisferio derecho oculto',inferior:'Vista inferior (ventral)',superior:'Vista superior (dorsal)'}[name];if(reduced){camera.position.copy(desiredPosition);controls.target.copy(desiredTarget);desiredPosition=null;}update(false);}
 controls.addEventListener('start',()=>{desiredPosition=null;document.querySelector('#orientation').textContent='Vista libre · orientación en los ejes A / L / S';});
 function update(focus){const a=activeRegions(),ae=activeEdges();const hi0=highlightId(),deep0=hi0&&regions[hi0].type!=='cortical';cortical.forEach(m=>{m.visible=state.layers.cortex&&sideVisible(m.userData.side);m.material.opacity=deep0?Math.min(state.opacity,.12):state.opacity;});refs.forEach(m=>m.visible=state.layers.reference&&sideVisible(m.userData.side));const hi=highlightId(),isolated=!!hi&&!state.revealed;glowing=[];for(const [id,list] of Object.entries(meshes)){const active=a.includes(id),focusOn=id===hi;for(const m of list){m.visible=sideVisible(m.userData.side)&&state.layers[regions[id].type==='cortical'?'cortex':'subcortical'];m.material.opacity=focusOn?1:active?(hi?.72:.94):(isolated?.05:hi?.12:.26);m.material.emissiveIntensity=focusOn?.6:active?(hi?.1:.15):.01;m.material.depthWrite=active||focusOn;m.renderOrder=focusOn?4:0;if(focusOn)glowing.push(m);}labels[id].hidden=!state.layers.labels||!(active||focusOn)||!list.some(m=>m.visible);labels[id].classList.toggle('active',active);labels[id].classList.toggle('focus',focusOn);labels[id].setAttribute('aria-pressed',state.mode==='explore'&&state.selected===id);}
 for(const f of flows){f.line.visible=ae.includes(f.i)&&sideVisible(f.side)&&state.layers.circuits&&meshes[f.e[0]].some(m=>m.visible)&&meshes[f.e[1]].some(m=>m.visible);const strength=edgeStrength(f.e);f.line.material.opacity=gate()?.1:.2+.65*strength;f.dots.forEach(d=>d.visible=f.line.visible&&state.layers.flow&&!gate()&&strength>0);}
 if(hi&&state.view==='anatomy'&&hi!==lastFocus){lastFocus=hi;const side=state.hemisphere==='right'?'right':state.hemisphere==='left'?'left':camera.position.z>=0?'left':'right';const t=anchors[hi][side].clone().multiplyScalar(.85);const dir=camera.position.clone().sub(controls.target).normalize();desiredTarget=t;desiredPosition=t.clone().add(dir.multiplyScalar(6.4));if(reduced){camera.position.copy(desiredPosition);controls.target.copy(desiredTarget);desiredPosition=null;}}else if(!hi){lastFocus=null;}
 if(!hi&&focus&&state.view==='anatomy'&&!state.home&&!reduced){const side=state.hemisphere==='right'?'right':'left';let target=new THREE.Vector3();a.forEach(id=>target.add(anchors[id][side]));target.divideScalar(a.length||1).multiplyScalar(.25);desiredTarget=target;desiredPosition=camera.position.clone().multiplyScalar(.99);}resize();}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down;
 renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(Object.values(meshes).flat().filter(m=>m.visible));if(hits.length)selectRegion(hits[0].object.userData.id);});
 function positionLabels(){const w=host.clientWidth,h=host.clientHeight,side=state.hemisphere==='right'?'right':state.hemisphere==='left'?'left':camera.position.z>=0?'left':'right';const entries=[];for(const [id,label] of Object.entries(labels)){if(label.hidden)continue;const p=anchors[id][side].clone().project(camera);const ax=(p.x*.5+.5)*w,ay=(-p.y*.5+.5)*h;entries.push({id,label,ax,ay,left:ax<w*.5,y:Math.max(55,Math.min(h-100,ay))});}const badge=document.querySelector('#incentive'),reserve=badge&&!badge.hidden?badge.offsetTop+badge.offsetHeight-10:30;for(const isLeft of [true,false]){const list=entries.filter(x=>x.left===isLeft).sort((a,b)=>a.y-b.y);let lastY=isLeft?30:reserve;for(const x of list){x.y=Math.max(x.y,lastY+34);lastY=x.y;}if(lastY>h-85){const shift=lastY-(h-85);list.forEach(x=>x.y-=shift);}}
 leaders.setAttribute('viewBox',`0 0 ${w} ${h}`);leaders.innerHTML=entries.map(x=>{const half=x.label.offsetWidth/2,xPos=x.left?half+9:w-half-9;x.label.style.left=xPos+'px';x.label.style.top=x.y+'px';const end=xPos+(x.left?half:-half);return `<path d="M${x.ax},${x.ay} L${end},${x.y}" stroke="#${regions[x.id].color.toString(16)}" opacity=".55" fill="none"/><circle cx="${x.ax}" cy="${x.ay}" r="2" fill="#${regions[x.id].color.toString(16)}"/>`;}).join('');}
 function compass(){const el=document.querySelector('#anatomyAxes');if(!el)return;camera.updateMatrixWorld();const a=[['A','P',new THREE.Vector3(-1,0,0)],['S','I',new THREE.Vector3(0,1,0)],['L','R',new THREE.Vector3(0,0,1)]];el.innerHTML=a.map(([positive,negative,v])=>{v.transformDirection(camera.matrixWorldInverse);if(Math.hypot(v.x,v.y)<.25)return `<text x="45" y="49">${v.z>0?positive:negative} ⊙</text>`;return `<line x1="45" y1="45" x2="${45+v.x*27}" y2="${45-v.y*27}" stroke="#98adc3"/><text x="${45+v.x*36}" y="${49-v.y*36}">${positive}</text><text x="${45-v.x*36}" y="${49+v.y*36}" opacity=".5">${negative}</text>`;}).join('');}
 function animate(t){requestAnimationFrame(animate);const dt=Math.min((t-last)/1000,.04)||0;last=t;if(document.hidden||state.home||state.view!=='anatomy'||state.mode==='body')return;if(!state.flowPaused)phase+=dt*state.speed;if(desiredPosition){camera.position.lerp(desiredPosition,.075);controls.target.lerp(desiredTarget,.075);if(camera.position.distanceTo(desiredPosition)<.003){desiredPosition=null;}}controls.update();if(!reduced)for(const m of glowing)m.material.emissiveIntensity=.45+.3*(0.5+0.5*Math.sin(t*.004));for(const f of flows)if(f.line.visible)f.dots.forEach((d,i)=>{if(d.visible)d.position.copy(f.curve.getPoint(reduced?i/3:(phase*.22*edgeStrength(f.e)+i/3)%1));});positionLabels();compass();renderer.render(scene,camera);}
 requestAnimationFrame(animate);loading.hidden=true;update(false);return {update,preset,resetCamera:()=>preset('left')};
}
