// Guided explanations describe network contributions, not deterministic causal chains.
export const journeys = {
 study:{label:'Estudiar aunque cueste',scene:'Tienes que preparar un examen. Puedes resolver un problema difícil o releer algo que ya dominas.',alternative:'El problema se divide en pasos y recibes una pista. El coste percibido puede bajar; no cambia automáticamente tu capacidad.',concept:'Motivación de logro y esfuerzo cognitivo',source:['Westbrook et al., 2020','https://pmc.ncbi.nlm.nih.gov/articles/PMC7430502/'],steps:[
 {edge:23,title:'Mantener una meta y seleccionar una acción',signal:'La corteza prefrontal dorsolateral aporta información sobre la regla y la meta a circuitos del caudado. Esta entrada corticostriatal es principalmente glutamatérgica.',meaning:'Mantener «voy a resolver este ejercicio» ayuda a orientar la selección de acciones. Recordar una meta no garantiza que decidamos invertir esfuerzo.',change:'Una pista puede reducir la demanda de memoria de trabajo y facilitar organizar el siguiente paso.'},
 {edge:22,title:'Modular cuánto compensa el esfuerzo',signal:'La SNc envía proyecciones dopaminérgicas al estriado dorsal, incluido el caudado. La dopamina modula cómo funcionan estos circuitos; no transporta una orden literal de estudiar.',meaning:'La disposición a realizar trabajo cognitivo puede depender del balance entre beneficios y costes. Tener capacidad y querer usarla son cosas distintas.',change:'Al hacer el coste más manejable, la misma meta puede parecer más alcanzable. Esto no permite deducir un cambio concreto de dopamina.'},
 {edge:24,title:'Ajustar la acción a la demanda',signal:'La corteza mediocingulada anterior interactúa con el caudado en circuitos relacionados con esfuerzo y selección de acciones.',meaning:'Puedes persistir, cambiar de estrategia o descansar. La conducta depende también del sueño, los conocimientos y las condiciones del entorno.',change:'Una tarea dividida en pasos ofrece oportunidades de ajustar la estrategia y observar avances.'}],question:'Si un estudiante evita una tarea difícil, ¿qué podemos concluir?',options:['Que tiene poca dopamina.','Que conviene explorar costes, metas y contexto; la conducta sola no revela su dopamina.'],right:1,feedback:'La elección no permite medir un neurotransmisor. Esfuerzo percibido, expectativas, recursos y ambiente contribuyen a la decisión.'},
 curiosity:{label:'Aprender por curiosidad',scene:'Aparece una pregunta cuya respuesta deseas conocer, incluso sin puntos ni nota.',alternative:'Ahora conoces la respuesta de antemano. La incertidumbre informativa disminuye, aunque podrías seguir interesado en profundizar.',concept:'Motivación intrínseca y búsqueda de información',source:['Gruber et al., 2014','https://pmc.ncbi.nlm.nih.gov/articles/PMC4252494/'],steps:[
 {edge:0,title:'Anticipar información valiosa',signal:'La VTA proyecta dopamina al núcleo accumbens. En estudios de curiosidad participan regiones mesencefálicas SN/VTA y estriado ventral; la señal de fMRI no mide directamente dopamina.',meaning:'Obtener una respuesta puede funcionar como incentivo. La motivación no requiere siempre un premio material.',change:'Si la respuesta ya es conocida, puede reducirse el interés por obtener esa información concreta.'},
 {edge:21,title:'Relacionar motivación y memoria',signal:'Los sistemas mesencefálicos se relacionan con el hipocampo. Aquí se representa una relación simplificada, con posibles relevos y otras fuentes catecolaminérgicas.',meaning:'Un estado de curiosidad puede favorecer el aprendizaje y el recuerdo; no asegura recordar todo ni demuestra por sí solo una causa dopaminérgica.',change:'Conocer ya la respuesta cambia la oportunidad de aprender algo nuevo, pero no apaga el hipocampo.'},
 {edge:20,title:'Usar el contexto para orientar la búsqueda',signal:'El hipocampo aporta información contextual al estriado ventral, incluido el accumbens.',meaning:'Lo que recuerdas de un tema ayuda a decidir qué información merece explorar después.',change:'Puedes reformular la pregunta y buscar una explicación más profunda en lugar de repetir un dato conocido.'}],question:'¿La actividad de SN/VTA observada con fMRI prueba que se liberó una cantidad concreta de dopamina?',options:['No: la señal BOLD es indirecta y no identifica por sí sola un neurotransmisor.','Sí: equivale a medir dopamina.'],right:0,feedback:'La fMRI informa sobre cambios hemodinámicos asociados con actividad neural. No es un registro directo de liberación dopaminérgica.'},
 incentive:{label:'Querer mirar una notificación',scene:'Mientras estudias, aparece una notificación asociada a mensajes interesantes. Sientes ganas de abrirla.',alternative:'Abres el mensaje y resulta poco interesante. El deseo previo de comprobarlo puede haber sido intenso aunque disfrutes poco del resultado.',concept:'Incentivo aprendido: wanting y liking',source:['Berridge y Robinson, 2016','https://pmc.ncbi.nlm.nih.gov/articles/PMC5171207/'],steps:[
 {edge:25,title:'Dar relevancia a una señal aprendida',signal:'El complejo amigdalino envía información al estriado ventral. Esta relación contribuye a vincular señales aprendidas con resultados relevantes; no es una proyección dopaminérgica.',meaning:'Una señal que antes era neutra puede adquirir capacidad de atraer tu atención y orientar la aproximación.',change:'Un resultado poco interesante puede contribuir a actualizar lo que esperas de señales futuras, según tu historial de aprendizaje.'},
 {edge:0,title:'Favorecer la búsqueda del incentivo',signal:'La VTA envía proyecciones dopaminérgicas al accumbens, dentro de una red más amplia de motivación y aprendizaje.',meaning:'Sentir ganas de comprobar un mensaje no equivale a disfrutarlo. El impulso de aproximación y el impacto agradable pueden disociarse parcialmente.',change:'Puedes haber querido abrirlo mucho y, al leerlo, disfrutar poco: querer y gustar no son una única variable.'},
 {edge:5,title:'Actualizar el valor esperado',signal:'La corteza orbitofrontal aporta al accumbens información relacionada con resultados esperados y su valor actual, mediante entradas principalmente glutamatérgicas.',meaning:'La valoración depende del contexto. Un mensaje puede ser atractivo y, a la vez, competir con una meta de estudio.',change:'El resultado recibido puede modificar las expectativas futuras. Un ensayo aislado no borra necesariamente una asociación aprendida.'}],question:'Si deseas mucho abrir el mensaje, pero después te gusta poco, ¿hay contradicción?',options:['Sí: más deseo siempre implica más placer.','No: wanting y liking son componentes parcialmente separables.'],right:1,feedback:'El deseo de obtener algo y su impacto hedónico pueden diferir. Este ejemplo no diagnostica adicción ni mide neurotransmisores.'},
 emotion:{label:'Sentir nervios antes de un examen',scene:'Antes de entrar al examen, recuerdas una experiencia difícil y percibes la situación como una amenaza.',alternative:'Reinterpretas: «Es una oportunidad de mostrar lo aprendido; puedo empezar por una pregunta manejable». El contexto y tus recursos siguen importando.',concept:'Valoración emocional, contexto y regulación',source:['Buhle et al., 2014','https://pubmed.ncbi.nlm.nih.gov/23765157/'],steps:[
 {edge:12,title:'Relacionar contexto y relevancia emocional',signal:'El hipocampo y el complejo amigdalino interactúan: memoria contextual y relevancia emocional se influyen mutuamente.',meaning:'Recordar una experiencia negativa puede contribuir a valorar el examen como amenazante. La amígdala no contiene por sí sola el miedo.',change:'Una interpretación alternativa puede cambiar el significado del recuerdo para la situación presente, sin eliminarlo.'},
 {edge:10,title:'Coordinar parte de la respuesta corporal',signal:'La amígdala se relaciona con el hipotálamo y otros sistemas que participan en respuestas autonómicas y endocrinas. El esquema omite muchos relevos y regiones.',meaning:'La valoración de amenaza puede acompañarse de cambios corporales. La experiencia emocional integra cuerpo, interpretación y contexto; no es solo esta flecha.',change:'La respuesta corporal puede variar con la valoración y el tiempo. Reinterpretar no garantiza una reducción inmediata de los nervios.'},
 {edge:7,title:'Reinterpretar mediante una red de control',signal:'Regiones prefrontales participan en mantener interpretaciones alternativas y modular redes emocionales. La relación dlPFC–amígdala se dibuja con relevos: no es un freno directo único.',meaning:'Reevaluar el significado de la situación puede cambiar su impacto afectivo. Regular una emoción no equivale a apagarla.',change:'Pensar «puedo empezar por lo que sé» puede apoyar una conducta de aproximación. El efecto depende de la persona y de la situación.'}],question:'¿Qué explica mejor la regulación emocional?',options:['Una red modifica la interpretación y la respuesta, con resultados variables.','La dlPFC apaga directamente la amígdala y elimina el miedo.'],right:0,feedback:'La reevaluación implica una red distribuida. El mapa es una explicación simplificada; no una secuencia obligatoria ni una predicción individual.'}
};
