// Anatomical identity is independent of membership in a functional circuit.
export const families={
 prefrontal:{name:'Corteza prefrontal',color:'#79aaff',description:'Lóbulo frontal → corteza prefrontal → región dorsolateral / orbitofrontal.'},
 cingulate:{name:'Corteza cingulada',color:'#58d6c2',description:'Corteza cingulada → porciones anterior y mediocingulada anterior. No se trata aquí como una subdivisión de la OFC.'},
 striatum:{name:'Estriado',color:'#ef8cba',description:'Ganglios basales → estriado → ventral (NAcc) / dorsal (caudado).'},
 midbrain:{name:'Mesencéfalo',color:'#ffd16a',description:'Tronco encefálico → mesencéfalo → VTA / sustancia negra pars compacta.'},
 diencephalon:{name:'Diencéfalo',color:'#ffa36c',description:'Diencéfalo → hipotálamo; el tálamo gris se muestra como referencia.'},
 hippocampal:{name:'Formación hipocampal',color:'#c1a0ff',description:'Telencéfalo → corteza temporal medial → formación hipocampal (alocorteza).'},
 amygdala:{name:'Complejo amigdalino',color:'#f0a297',description:'Telencéfalo → núcleos de la región temporal medial → complejo amigdalino.'}
};
export const regions={
 pfc:{name:'Región prefrontal dorsolateral',short:'dlPFC',family:'prefrontal',map:[100,100],type:'cortical',color:0x79aaff,location:'Superficie lateral anterior del lóbulo frontal; bilateral.',hierarchy:'Lóbulo frontal → corteza prefrontal → región dorsolateral',description:'Participa en mantener reglas y metas y orientar la conducta. No representa toda la corteza prefrontal ni es un núcleo profundo.',process:'Mantenimiento de metas, memoria de trabajo y control de la acción.',representation:'Parcela rostral del giro frontal medio (Desikan–Killiany), usada como referencia aproximada de dlPFC; sus límites no equivalen a una delimitación funcional completa.',caution:'La dlPFC y la OFC comparten familia prefrontal; no son dos nombres de una misma región.',connections:['ofc','amcc','nacc','caudate','amyg','hipp']},
 ofc:{name:'Corteza orbitofrontal',short:'OFC',family:'prefrontal',map:[100,250],type:'cortical',color:0xa4c5ff,location:'Superficie inferior del lóbulo frontal, sobre las órbitas; bilateral.',hierarchy:'Lóbulo frontal → corteza prefrontal → corteza orbitofrontal',description:'Contribuye a representar resultados esperados y su valor en el contexto actual. La relación entre metas, valoración y acción se distribuye en varias regiones.',process:'Valoración de resultados, expectativas y flexibilidad ante cambios.',representation:'Parcelas orbitofrontales medial y lateral de Desikan–Killiany. No se identifica toda la corteza ventromedial con la OFC.',caution:'No es una estructura externa a la PFC. El valor de un estímulo cambia con el estado y la experiencia.',connections:['pfc','nacc','amyg','vta','acc']},
 acc:{name:'Corteza cingulada anterior',short:'ACC',family:'cingulate',map:[285,85],type:'cortical',color:0x58d6c2,location:'Superficie medial, por delante y alrededor de la rodilla del cuerpo calloso; bilateral.',hierarchy:'Corteza cingulada → porción anterior',description:'Integra información afectiva, autonómica y de valoración. Sus subregiones no son intercambiables y no explican por sí solas el control.',process:'Integración afectiva y valoración de resultados.',representation:'Parcela G_and_S_cingul-Ant del atlas Destrieux.',caution:'Buena parte de lo denominado «dACC» en estudios funcionales alcanza la mediocingulada anterior (aMCC), que aquí se distingue.',connections:['ofc','amcc','nacc']},
 amcc:{name:'Corteza mediocingulada anterior',short:'aMCC',family:'cingulate',map:[475,85],type:'cortical',color:0x91e9da,location:'Superficie medial, por encima del cuerpo calloso y posterior a la ACC rostral; bilateral.',hierarchy:'Corteza cingulada → mediocingulada → porción anterior',description:'Contribuye al ajuste de la acción y a integrar demandas, costes y control. Participa en circuitos que relacionan esfuerzo y resultados.',process:'Asignación de esfuerzo, seguimiento del conflicto y ajuste de la conducta.',representation:'Parcela G_and_S_cingul-Mid-Ant de Destrieux. Correspondencia anatómica aproximada con áreas funcionales descritas como dACC/aMCC.',caution:'«ACC», «dACC» y «aMCC» dependen de la nomenclatura; no se deben usar como sinónimos anatómicos perfectos.',connections:['pfc','acc','nacc','caudate']},
 nacc:{name:'Núcleo accumbens',short:'NAcc',family:'striatum',map:[300,250],type:'subcortical',color:0xef8cba,location:'Estriado ventral, anterior y ventral respecto al caudado; bilateral.',hierarchy:'Ganglios basales → estriado → estriado ventral → núcleo accumbens',description:'Integra señales relacionadas con incentivos y acción. Participa en aproximación, esfuerzo y aprendizaje; no es un «centro del placer».',process:'Motivación de incentivo y disposición a actuar.',representation:'Segmentación bilateral Accumbens-area de aseg. No resuelve core, shell ni hotspots hedónicos.',caution:'Core no equivale exclusivamente a wanting ni shell exclusivamente a liking. Los hotspots son zonas pequeñas y no ocupan todo el núcleo.',connections:['vta','ofc','pfc','acc','amcc','amyg','hipp']},
 caudate:{name:'Núcleo caudado',short:'Caudado',family:'striatum',map:[490,250],type:'subcortical',color:0xffbdd8,location:'Estructura curva del estriado dorsal que acompaña al ventrículo lateral; bilateral.',hierarchy:'Ganglios basales → estriado → estriado dorsal → núcleo caudado',description:'Participa en circuitos asociativos de selección de acciones y aprendizaje. La motivación cognitiva no se limita al NAcc ni a la vía mesolímbica.',process:'Aprendizaje acción–resultado y decisiones sobre esfuerzo cognitivo.',representation:'Segmentación bilateral Caudate de aseg.',caution:'No es una parte del NAcc. Comparte el estriado, pero pertenece a su división dorsal.',connections:['snc','pfc','amcc']},
 vta:{name:'Área tegmental ventral',short:'VTA*',family:'midbrain',map:[245,415],type:'subcortical',color:0xffd16a,location:'Mesencéfalo ventromedial, cercano a la línea media; no está en el hipotálamo.',hierarchy:'Tronco encefálico → mesencéfalo → área tegmental ventral',description:'Contiene poblaciones dopaminérgicas y otras no dopaminérgicas. Sus proyecciones contribuyen a motivación y aprendizaje.',process:'Señales de incentivo y, en determinadas poblaciones, errores de predicción.',representation:'Marcadores bilaterales discontinuos aproximados: aseg no delimita la VTA. No representan una segmentación ni su extensión real.',caution:'VTA → NAcc es mesolímbica; VTA → corteza prefrontal es mesocortical. No todas las flechas de la red transportan dopamina.',connections:['nacc','pfc','ofc','hipp','hypo']},
 snc:{name:'Sustancia negra, pars compacta',short:'SNc*',family:'midbrain',map:[445,415],type:'subcortical',color:0xffe4a0,location:'Mesencéfalo, más lateral respecto a la VTA; bilateral.',hierarchy:'Tronco encefálico → mesencéfalo → sustancia negra → pars compacta',description:'Es una fuente importante de dopamina para el estriado dorsal. Participa en aprendizaje y control de acciones, además de funciones motoras.',process:'Modulación dopaminérgica de circuitos del estriado dorsal.',representation:'Marcadores discontinuos aproximados; no hay una segmentación de SNc en este conjunto.',caution:'La vía nigroestriada no es idéntica a la vía VTA–NAcc. Pars compacta y pars reticulata son divisiones diferentes.',connections:['caudate']},
 hypo:{name:'Hipotálamo',short:'Hipotálamo*',family:'diencephalon',map:[650,430],type:'subcortical',color:0xffa36c,location:'Diencéfalo ventral, inferior al tálamo, a ambos lados del tercer ventrículo.',hierarchy:'Diencéfalo → hipotálamo → múltiples núcleos',description:'Integra señales del cuerpo y contribuye a la regulación autonómica y endocrina. Necesidades, aprendizaje y oportunidades ambientales interactúan.',process:'Balance energético y comunicación cerebro–cuerpo.',representation:'Marcadores aproximados; no se usa la etiqueta VentralDC como si fuera exclusivamente hipotálamo.',caution:'La saciedad no implica que el hipotálamo esté inactivo ni que deje de haber motivación por comida.',connections:['amyg','vta','acc']},
 amyg:{name:'Complejo amigdalino',short:'Amígdala',family:'amygdala',map:[680,275],type:'subcortical',color:0xf0a297,location:'Temporal medial anterior, por delante de la cabeza del hipocampo; bilateral.',hierarchy:'Telencéfalo → núcleos temporales mediales → complejo amigdalino',description:'Participa en aprendizaje y relevancia de estímulos apetitivos y aversivos, en interacción con otras regiones.',process:'Aprendizaje emocional y coordinación de respuestas.',representation:'Segmentación bilateral Amygdala de aseg; no separa sus distintos núcleos.',caution:'No es «el centro del miedo». Tampoco es una parte del hipocampo, aunque estén próximos.',connections:['pfc','hipp','hypo','ofc','nacc']},
 hipp:{name:'Hipocampo',short:'Hipocampo',family:'hippocampal',map:[685,110],type:'deepCortex',color:0xc1a0ff,location:'Temporal medial, con un eje longitudinal curvo posterior a la amígdala; bilateral.',hierarchy:'Telencéfalo → corteza temporal medial → formación hipocampal',description:'Aporta memoria y contexto a la valoración de situaciones. Su profundidad no lo convierte anatómicamente en un núcleo subcortical.',process:'Memoria episódica, contexto y relación entre motivación y aprendizaje.',representation:'Etiqueta Hippocampus de aseg. No se delimitan los subcampos hipocampales ni toda la corteza entorrinal.',caution:'Es alocorteza, distinta de la neocorteza y del complejo amigdalino.',connections:['amyg','pfc','nacc','vta']}
};
// [source, target, pedagogical flow, connection class, explanation]. Dashed links explicitly include relays.
export const edges=[
 ['vta','nacc','up','da','Vía mesolímbica: proyección dopaminérgica VTA → estriado ventral.'],
 ['vta','pfc','up','da','Vía mesocortical: proyecciones dopaminérgicas hacia regiones prefrontales.'],
 ['vta','ofc','up','da','Proyección dopaminérgica mesocortical; la OFC forma parte de la PFC.'],
 ['nacc','ofc','up','indirect','Retorno funcional al córtex mediante relevos, incluido pálido ventral y tálamo; no es una proyección dopaminérgica directa.'],
 ['nacc','acc','up','indirect','Bucle estriado–pálido–tálamo–corteza, simplificado.'],
 ['ofc','nacc','down','other','Entrada corticostriatal principalmente glutamatérgica; no equivale a un freno inhibitorio simple.'],
 ['pfc','nacc','down','indirect','Influencia de redes prefrontales sobre el estriado ventral, representada con relevos: no es una proyección exclusiva de dlPFC.'],
 ['pfc','amyg','down','indirect','Modulación prefrontal de la amígdala; puede implicar regiones prefrontales mediales y otras vías intermedias.'],
 ['pfc','ofc','cortical','other','Interacción entre regiones corticales; no es un flujo cortical → subcortical.'],
 ['acc','nacc','down','other','Relación cinguloestriatal no dopaminérgica.'],
 ['amyg','hypo','subcortical','other','Relación entre sistemas subcorticales que contribuye a respuestas corporales.'],
 ['amyg','pfc','up','indirect','Información emocional hacia redes prefrontales; esquema funcional con posibles relevos.'],
 ['hipp','amyg','context','other','Interacción temporal medial entre contexto y relevancia emocional.'],
 ['hipp','pfc','up','indirect','Relación funcional de memoria contextual y metas; no se representa un único tracto.'],
 ['hypo','vta','subcortical','other','Las señales del estado corporal modulan circuitos motivacionales mediante vías heterogéneas.'],
 ['amyg','hipp','context','other','Interacción entre relevancia emocional y memoria contextual.'],
 ['ofc','amyg','down','other','Interacción orbitofrontal–amigdalina; no es dopamina ni inhibición por definición.'],
 ['amcc','nacc','down','other','Interacción cinguloestriatal en esfuerzo y ajuste de la acción.'],
 ['pfc','amcc','cortical','other','Interacción cortical entre metas y demandas de control.'],
 ['acc','amcc','cortical','other','Interacción entre porciones cinguladas distintas.'],
 ['hipp','nacc','context','other','Aporte hipocampal de información contextual al estriado ventral.'],
 ['vta','hipp','up','indirect','Relación mesencéfalo–hipocampo simplificada; otras fuentes catecolaminérgicas también pueden contribuir.'],
 ['snc','caudate','up','da','Vía nigroestriada: proyección dopaminérgica de SNc hacia estriado dorsal.'],
 ['pfc','caudate','down','other','Entrada corticostriatal asociativa, principalmente glutamatérgica.'],
 ['amcc','caudate','down','other','Interacción cinguloestriatal relacionada con selección de acción y esfuerzo.'],
 ['amyg','nacc','subcortical','other','Entrada amigdalina al estriado ventral que aporta información de relevancia aprendida; no es una proyección dopaminérgica.'],
 ['ofc','acc','cortical','other','Interacción entre cortezas orbitofrontal y cingulada anterior.'],
 ['acc','hypo','down','indirect','Relación funcional cortical–autonómica, con posibles relevos; no se representa un tracto único.']
];
export const edgeColor=e=>e[3]==='da'?'#ffd16a':e[3]==='indirect'?'#aab8c9':e[2]==='down'?'#85acff':e[2]==='up'?'#76e8c7':'#c9b4dc';
